name: MERIT
data_path: /projects/mhpi/data/${name}
zone: 75
create_edges:
  buffer: 0.3334
  dx: 2000
  edges: ${data_path}/zarr/graph/edges/
  flowlines: ${data_path}/raw/flowlines
create_N:
  run_whole_zone: False
  drainage_area_treshold: 0.1
  filter_based_on_dataset: True
  gage_buffered_flowline_intersections: ${data_path}/gage_information/gage_flowline_intersections/gage_9322_intersection.shp
  gage_coo_indices: ${data_path}/zarr/gage_coo_indices
  pad_gage_id: True
  obs_dataset: ${data_path}/gage_information/obs_csvs/gages3000Info.csv
  obs_dataset_output: ${data_path}/gage_information/formatted_gage_csvs/gages_3000_merit_info.csv
  zone_obs_dataset: ${data_path}/gage_information/formatted_gage_csvs/${zone}.csv
create_TMs:
  MERIT:
    save_sparse: True
    TM: ${data_path}/zarr/TMs/MERIT_FLOWLINES_${zone}
    shp_files: ${data_path}/raw/basins/cat_pfaf_${zone}_MERIT_Hydro_v07_Basins_v01_bugfix1.shp
create_streamflow:
  version: merit_conus_v1.1
  data_store: ${data_path}/streamflow/zarr/${create_streamflow.version}/${zone}
  obs_attributes: ${data_path}/gage_information/MERIT_basin_area_info
  predictions: /projects/mhpi/hjj5218/model_output/conus_zarr/${zone}
  start_date: 01-01-1980
  end_date: 12-31-2020
extensions:
  - soils_data
  - pet_forcing
  - global_dhbv_static_inputs
  - incremental_drainage_area
# Hydra Config ------------------------------------------------------------------------#
hydra:
  help:
    app_name: marquette
    header: == ${hydra.help.app_name} ==
    template: |-
      ${hydra.help.header}
  
      A data pipeline tool used to generate inputs to dMC river routing
      By Tadd Bindas

      ${hydra.help.footer}
    footer: |-
      Powered by Hydra (https://hydra.cc)
      Use --hydra-help to view Hydra specific help
  job:
    name: ${name}
  run:
    dir: ../runs/${hydra.job.name}_${zone}/${now:%Y-%m-%d_%H-%M-%S}
