name: MERIT
basin: srb
data_path: /data/tkb5476/projects/marquette/data/
dx: 2000
buffer: 0.3334
date_codes: ${data_path}/date_codes.json
needs_clip: False
crs:
  wgs: epsg:4326
  utm18: epsg:32618
file_paths:
  flow_lines: ???
  basins: ???
save_paths:
  gage_locations: /mnt/sdb1/Database/PKDN/grid/gages_II_locations.csv
  flow_lines: ${data_path}/${name}/graph/conus/${name}_merit_flowlines.shp
##  basins: ${data_path}/${name}/basins/pfaf_7_merit_1053.shp
  huc_10: /data/tkb5476/projects/marquette/data/HUC/huc_10_watersheds_${name}.shp
  streamflow: ${data_path}/${name}/streamflow/${basin}_pre_interpolate.csv
  huc_to_merit_tm: ${data_path}/${name}/streamflow/${basin}_huc_10_merit_TM.csv
  merit_to_river_graph_tm: ${data_path}/${name}/streamflow/merit_to_${basin}_river_graph_TM.csv
csv:
  edges: ${data_path}/${name}/processed_csvs/${basin}_edges.csv
  mapped_streamflow: ${data_path}/${name}/processed_csvs/${basin}_mapped_streamflow.csv
