name: hydrofabric
data_path: /data/tkb5476/projects/marquette/data/${name}
basin: small_basin
dx: 2000
buffer: 0.3334
crs:
  wgs: epsg:4326
  utm18: epsg:32618
file_paths:
  gage_locations: ${data_path}/${basin}/raw/gages_II_small_outflow.shp
  flow_lines: ${data_path}/${basin}/raw/gages_II_small_srb.shp
  basins: ${data_path}/${basin}/raw/huc_10_small.shp
#csv:
#  edges:  ${output_path}/edges.csv
#  network: ${output_path}/network_matrix.csv
#  runoff_matrix: ${output_path}/runoff_matrix.csv
#  basin_matrix: ${output_path}/basin_matrix.csv
#  mass_transfer_matrix: ${output_path}/mass_transfer_matrix.csv
#  attributes: ${output_path}/attributes.csv
#  forcings: ${output_path}/_q_prime_tau_post_process.csv
