name: MERIT
data_path: /data/tkb5476/projects/marquette/data/
dx: 2000
buffer: 0.3334
units: mm/day
date_codes: ${data_path}/date_codes.json
is_streamflow_split: true
start_date: 01-01-1980
end_date: 12-31-2019
#end_date: 12-31-2020
num_cores: 20
continent: 7
area: 3
num_partitions: 64
save_name: ${continent}${area}
individual_streamflow_files: False
save_paths:
  attributes: ${data_path}/streamflow/attributes_dpl_v2.csv
  basins: ${data_path}/${name}/raw/basins/cat_pfaf_${continent}${area}_MERIT_Hydro_v07_Basins_v01_bugfix1.shp
  flow_lines: ${data_path}/${name}/raw/flowlines
  huc10: ${data_path}/HUC/huc_10_CONUS.shp
  streamflow_files: ${data_path}/streamflow/predictions/dpl_v2/
zarr:
  csr_matrix: ${data_path}/${name}/zarr/graph/csr_network_matrix/
  edges: ${data_path}/${name}/zarr/graph/edges/
  HUC_TM: ${data_path}/${name}/zarr/TMs/PFAF_${continent}${area}
  MERIT_TM: ${data_path}/${name}/zarr/TMs/MERIT_FLOWLINES_${continent}${area}
  streamflow: ${data_path}/streamflow/zarr/dpl_v2/${save_name}
