name: MERIT
basin: srb
data_path: /data/tkb5476/projects/marquette/data/${name}
dx: 2000
buffer: 0.3334
date_codes: /data/tkb5476/data/MERIT/date_codes.json
needs_clip: False
crs:
  wgs: epsg:4326
  utm18: epsg:32618
file_paths:
  flow_lines: ???
  basins: ???
save_paths:
  gage_locations: /mnt/sdb1/Database/PKDN/grid/gages_II_locations.csv
  runoff_raw: ${data_path}/runoff/raw/
  flow_lines: ${data_path}/graph/srb/srb_rivers.shp
  runoff_dir: ${data_path}/runoff/raw/2001/2001_train/
  runoff_clipped: ${data_path}/runoff/clipped/2001/${data.basin_name}/
  runoff_file: ???
  basins: ${data_path}/basins/srb/pfaf7_srb.shp
  huc_2: ${data_path}/HUC/SRB/SRB_HUC2.shp
csv:
  edges: ${data_path}/processed_csvs/${basin}.csv
