# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri May  3 06:16:27 2024
# ------------------------------------------------

package:
  name: wheel
  version: 0.43.0
source:
  sha256: 465ef92c69fa5c5da2d1cf8ac40559a8c940886afcef87dcf14b9470862f1d85
  url: https://pypi.io/packages/source/w/wheel/wheel-0.43.0.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  number: '0'
  string: py311h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.3.11 h06a4308_0
    - flit-core 3.9.0 py311hee27c6d_1
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.13 h7f8727e_1
    - python 3.11.9 h955ad1f_0
    - python-installer 0.7.0 py311h06a4308_0
    - readline 8.2 h5eee18b_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
    - wheel --help
    - wheel version
  imports:
    - wheel
    - wheel.cli
    - wheel.vendored
    - wheel.vendored.packaging
  requires:
    - pip
about:
  description: "This library is the reference implementation of the Python wheel packaging\
    \ standard,\nas defined in PEP 427.\nIt has two different roles:\n  1. A setuptools\
    \ extension for building wheels that provides the bdist_wheel setuptools command\n\
    \  2. A command line tool for working with wheel files\n"
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b62b8a80-eb62-47c8-8513-4b67175a9d9d
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/wheel-feedstock.git
  sha: 6008a9de39dc8e51f369a2ab05d122451ef07532
  skip-lints:
    - missing_wheel
