python:
  - 3.11
python_impl:
  - cpython
libffi:  # [win]
  - 3.4  # [win] 
numpy:
  - 1.21
MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.14            # [osx and x86_64]
CONDA_BUILD_SYSROOT:  # [osx and x86_64]
  - /opt/MacOSX10.14.sdk        # [osx and x86_64]

